# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RegisterView.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import datetime

from PyQt5 import QtCore, QtGui, QtWidgets
from library import connection, messagebox
import time
import resources


class Ui_MainWindow(object):
    def registered(self):
        cur, con = connection()

        username = self.username.text()
        nik = self.nik.text()
        tanggal_lahir = self.tglLahir.text()
        save_tgl = datetime.datetime.strptime(tanggal_lahir, "%d/%m/%Y")
        jenis_kelamin = str(self.jenisKelamin.currentText())
        jabatan = self.jabatan.text()
        password = self.password.text()
        confirm_password = self.confirmPassword.text()

        get_username = "SELECT username FROM user where username = %s"
        cur.execute(get_username, username)
        result_username = cur.fetchall()

        if (result_username != ()):
            return messagebox('PERINGATAN', 'Username sudah terdaftar!')

        get_nik = "SELECT nik FROM user where nik = %s"
        cur.execute(get_nik, nik)
        result_nik = cur.fetchall()

        if (result_nik != ()):
            return messagebox('PERINGATAN', 'NIK sudah terdaftar!')

        if (password != confirm_password):
            return messagebox('PERINGATAN', 'Password yang anda masukkan tidak sama!')

        if (username == '' or nik == '' or tanggal_lahir == '' or jenis_kelamin == '' or jabatan == '' or password == '' or confirm_password == ''):
            return messagebox('PERINGATAN', 'Ada kolom yang kosong!')

        self.btnRegister.setEnabled(False)
        self.btnLogin.setEnabled(False)

        insert = (username, nik, save_tgl.date(), jenis_kelamin, jabatan, confirm_password)
        sql = "INSERT INTO user (username, nik, tanggal_lahir, jenis_kelamin, jabatan, password) VALUES (%s, %s, %s, %s, %s, %s)"
        data = cur.execute(sql, insert)
        if (data):
            messagebox('SUKSES', "Anda Berhasil Registrasi!")
            self.username.setText('')
            self.nik.setText('')
            self.jenisKelamin.setCurrentIndex(0)
            self.jabatan.setText('')
            self.password.setText('')
            self.confirmPassword.setText('')
            from scrapingView import Ui_MainWindow
            self.window = QtWidgets.QMainWindow()
            self.ui = Ui_MainWindow()
            self.ui.setupUi(self.window)
            self.window.show()
        else:
            messagebox('GAGAL', "Anda Gagal Melakukan Registrasi!")
            self.btnRegister.setEnabled(True)
            self.btnLogin.setEnabled(True)

    def gotoLogin(self):
        from LoginView import Ui_MainWindow
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 547)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -10, 801, 571))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(230, 20, 351, 511))
        self.label_2.setStyleSheet("background-color: rgba(255, 255, 255, 50%);\n"
"border-radius: 15px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(360, 20, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(230, 60, 351, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(280, 100, 51, 16))
        self.label_5.setObjectName("label_5")
        self.username = QtWidgets.QLineEdit(self.centralwidget)
        self.username.setGeometry(QtCore.QRect(280, 120, 251, 25))
        self.username.setStyleSheet("border-radius: 5px;")
        self.username.setObjectName("username")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(280, 150, 51, 16))
        self.label_6.setObjectName("label_6")
        self.nik = QtWidgets.QLineEdit(self.centralwidget)
        self.nik.setGeometry(QtCore.QRect(280, 170, 251, 25))
        self.nik.setStyleSheet("border-radius: 5px;")
        self.nik.setObjectName("nik")
        rx = QtCore.QRegExp("[0-9]{16}")
        onlyInt = QtGui.QRegExpValidator(rx)
        self.nik.setValidator(onlyInt)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(280, 200, 61, 16))
        self.label_7.setObjectName("label_7")
        self.tglLahir = QtWidgets.QDateEdit(self.centralwidget)
        self.tglLahir.setGeometry(QtCore.QRect(280, 220, 251, 25))
        self.tglLahir.setStyleSheet("border-radius: 5px;")
        self.tglLahir.setCalendarPopup(True)
        self.tglLahir.setObjectName("tglLahir")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(280, 250, 71, 16))
        self.label_8.setObjectName("label_8")
        self.jenisKelamin = QtWidgets.QComboBox(self.centralwidget)
        self.jenisKelamin.setGeometry(QtCore.QRect(280, 270, 251, 25))
        self.jenisKelamin.setStyleSheet("border-radius: 5px;")
        self.jenisKelamin.setObjectName("jenisKelamin")
        self.jenisKelamin.addItem("")
        self.jenisKelamin.addItem("")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(280, 300, 51, 16))
        self.label_9.setObjectName("label_9")
        self.jabatan = QtWidgets.QLineEdit(self.centralwidget)
        self.jabatan.setGeometry(QtCore.QRect(280, 320, 251, 25))
        self.jabatan.setStyleSheet("border-radius: 5px;")
        self.jabatan.setObjectName("jabatan")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(280, 350, 51, 16))
        self.label_10.setObjectName("label_10")
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(280, 370, 251, 25))
        self.password.setStyleSheet("border-radius: 5px;")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(280, 400, 111, 16))
        self.label_11.setObjectName("label_11")
        self.confirmPassword = QtWidgets.QLineEdit(self.centralwidget)
        self.confirmPassword.setGeometry(QtCore.QRect(280, 420, 251, 25))
        self.confirmPassword.setStyleSheet("border-radius: 5px;")
        self.confirmPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirmPassword.setObjectName("confirmPassword")
        self.btnRegister = QtWidgets.QPushButton(self.centralwidget)
        self.btnRegister.setGeometry(QtCore.QRect(340, 460, 131, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnRegister.setFont(font)
        self.btnRegister.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.btnRegister.setObjectName("btnRegister")
        self.btnRegister.clicked.connect(self.registered)
        self.btnLogin = QtWidgets.QPushButton(self.centralwidget)
        self.btnLogin.setGeometry(QtCore.QRect(310, 490, 191, 23))
        self.btnLogin.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);")
        self.btnLogin.setObjectName("btnLogin")
        self.btnLogin.clicked.connect(self.gotoLogin)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/newPrefix/dipake.jpg\"/></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "SIGN UP"))
        self.label_4.setText(_translate("MainWindow", "Pastikan semua kolom terisi!"))
        self.label_5.setText(_translate("MainWindow", "Username"))
        self.label_6.setText(_translate("MainWindow", "NIK"))
        self.label_7.setText(_translate("MainWindow", "Tanggal Lahir"))
        self.tglLahir.setDisplayFormat(_translate("MainWindow", "d/M/yyyy"))
        self.label_8.setText(_translate("MainWindow", "Jenis Kelamin"))
        self.jenisKelamin.setItemText(0, _translate("MainWindow", "Laki-Laki"))
        self.jenisKelamin.setItemText(1, _translate("MainWindow", "Perempuan"))
        self.label_9.setText(_translate("MainWindow", "Jabatan"))
        self.label_10.setText(_translate("MainWindow", "Password"))
        self.label_11.setText(_translate("MainWindow", "Konfirmasi Password"))
        self.btnRegister.setText(_translate("MainWindow", "REGISTER"))
        self.btnLogin.setText(_translate("MainWindow", "Sudah punya akun? Masuk disini!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
